package org.myFirstHibernate.dto;

import org.hibernate.annotations.CollectionId;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import javax.persistence.*;
import java.util.*;

@Entity
public class UserDetailsCollection {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int userID;
    private String username;
   /* @ElementCollection
    @JoinTable(name = "USER_ADDRESS", joinColumns = @JoinColumn(name = "USER_ID_FK"))
    private Set<Address> listOfAddress = new HashSet<>();*/

    @ElementCollection
    @JoinTable(name = "USER_ADDRESS", joinColumns = @JoinColumn(name = "USER_ID_FK")) // use customised column name than the generated one
    //customize from userDetailCollection_listOfAddress(Auto Generated by hibernate) to USER_ADDRESS
    @GenericGenerator(name = "hilo-gen", strategy = "hilo")
    @CollectionId(columns = {@Column(name = "ADDRESS_ID")}, generator = "hilo-gen", type =@Type(type="long"))
    private Collection<Address> listOfAddress = new ArrayList<>();

    public Collection<Address> getListOfAddress() {
        return listOfAddress;
    }

    public void setListOfAddress(Collection<Address> listOfAddress) {
        this.listOfAddress = listOfAddress;
    }

    public int getUserID() {
        return userID;
    }
    public void setUserID(int userID) {
        this.userID = userID;
    }
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
}